"""I am name nullable false

Revision ID: 5045ab4b9819
Revises: ba8b4221a86c
Create Date: 2023-06-09 08:51:11.851104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5045ab4b9819"
down_revision = "ba8b4221a86c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###
