"""empty message

Revision ID: 5202133ec3cf
Revises: c50afc1991af
Create Date: 2023-06-04 15:50:23.644068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5202133ec3cf"
down_revision = "c50afc1991af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.alter_column("rank", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "type_1", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column("HP", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("Defense", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("total", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("attack", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("sp_atk", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("sp_def", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("speed", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("generation", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("legendary", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.alter_column("legendary", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("generation", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("speed", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("sp_def", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("sp_atk", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("attack", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("total", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("Defense", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("HP", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "type_1", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column("rank", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
