"""empty message

Revision ID: 5c776f02d804
Revises: fff03f41ddcc
Create Date: 2023-05-31 13:04:24.082916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c776f02d804"
down_revision = "fff03f41ddcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Defense", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.drop_column("Defense")

    # ### end Alembic commands ###
