"""empty message

Revision ID: c50afc1991af
Revises: e809fcc52066
Create Date: 2023-06-04 15:47:56.836089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c50afc1991af"
down_revision = "e809fcc52066"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon_table", schema=None) as batch_op:
        batch_op.drop_column("id")

    # ### end Alembic commands ###
