"""empty message

Revision ID: fff03f41ddcc
Revises: 72b220da103c
Create Date: 2023-05-30 13:05:47.144987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff03f41ddcc'
down_revision = '72b220da103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_table', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('total')

    # ### end Alembic commands ###
